name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: abystoma/test
	  ref: branchname: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          repository: abystoma/test
          ref: branch
      - name: Greetings
        run: echo "$(<greetings.txt)"

      - name: Greetings
        run: echo "$(<greetings.txt)"
