name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: checkout/actions@v3
	with:
	  repository: abystoma/external-workflow
	  ref: branch
      - name: Greetings
        run: echo "$(<greetings.txt)"
