name: branch_checkout
on: [push]
jobs:
  external-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: abystoma/test
      - name: Greetings
        run: echo "$(<greetings.txt)"
